### ISSUE TITLE
Getting the TEC and geographic winds into IPE post-processing package

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/IPE#1]
The geographic winds are currently included in the standard IPE hdf5 outputs. Let's include these winds in the NetCDF files.
dataset    /apex/neutral_geographic_velocity1   for Eastward Wind (m/s)
dataset    /apex/neutral_geographic_velocity2   for Northward Wind (m/s)
dataset    /apex/neutral_geographic_velocity3   for Vertical Wind (m/s)
Sample files can be found under/scratch1/NCEPDEV/stmp2/Tzu-Wei.Fang/GSMWAM-IPE_dynamo

 Please also include TEC calculation at the same time.

**Comment by akubaryk** [comment]
Please verify the outputs here look okay: `/scratch1/NCEPDEV/stmp4/Adam.Kubaryk/tec_geo_test`

I will update the ipe_scripts branch and push the changes to wam-ipe_scripts if they look okay.

**Comment by twfang** [comment]
The TEC and neutral winds look good from these files. TEC looks identical to what I have before. Please commit the changes into the branch.

**Comment by akubaryk** [comment]
IPE branch has been pushed and wam-ipe_scripts branch of GSMWAM-IPE has been updated to include the new submodule pointer.
