### ISSUE TITLE
potential issue in varying Mesh_height_max

### ISSUE THREAD

**Issue by naomimaruyama** [SWPC-IPE/IPE#13]
Although [PR#290](https://github.com/SWPC-IPE/WAM-IPE/pull/290) has been merged and closed, we would need to further investigate the possible cause of the strange TEC reported in PR#290 when setting Mesh_height_max=1002 [km] (the default value is 782km). Furthermore, the 24hr WAM-IPE test run could not be finished within the 8hr walltime limit because the code hung up. 

The following 2 next steps were suggested during today's meeting:
(1) check Ne (and other variables) at different heights as the bad values could be happening only in a limited height range.
(2) try another test with an altitude below 1000km in case there is a hidden boundary at 1000km.

This issue has been assigned to @IonospherePlasmasphereElectrodynamics  and @rmontuoro.

**Comment by twfang** [comment]
The IPE levels are now sent to the SWPC mediator so there's no risk of inconsistency that was described in this issue. Also, the current outputs do not show the same problems in ionospheric parameters. Therefore, the issue is closed.
