### ISSUE TITLE
WAM-IPE Run for 2015 March and 2003 Nov Storms

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/IPE#18]
Just to document some results from the 2015 March storm run. The WAM-IPE run uses IPE code from the IPE_fixes branch with ksi set to 1 in the transport. It includes self-consistent electrodynamics and time-varying solar wind drivers. The IC for IPE came from a quiet 3-day run in 2013 March, not the original initial condition. The run starts from 20150316 to 20150320. 

Here are the geophysical conditions. 

![image](https://user-images.githubusercontent.com/22968399/74693233-1eb8bb00-51a8-11ea-8611-cabc7ef4a587.png)

20150316
![20150316](https://user-images.githubusercontent.com/22968399/74693323-a56d9800-51a8-11ea-986f-362d1b4ec1cd.png)

20150317
![20150317](https://user-images.githubusercontent.com/22968399/74693330-aacae280-51a8-11ea-8f49-7c8b3e641f44.png)

20150318
![20150318](https://user-images.githubusercontent.com/22968399/74693336-af8f9680-51a8-11ea-97cc-f8caa983ce56.png)

20150319
![20150319](https://user-images.githubusercontent.com/22968399/74693340-b4ece100-51a8-11ea-852b-049df48340a9.png)

20150320
![20150320](https://user-images.githubusercontent.com/22968399/74693347-ba4a2b80-51a8-11ea-991c-a9c47fc8a5dd.png)

**Comment by twfang** [comment]
Here are some results from the 2003 Nov Halloween storm using the same code and setups. The model went through the storm without crashing, which is super encouraging. 

2003/11/18
![20031118](https://user-images.githubusercontent.com/22968399/74783200-6ac83600-5262-11ea-8472-9c602aa3fabe.png)

2003/11/19
![20031119](https://user-images.githubusercontent.com/22968399/74783213-7156ad80-5262-11ea-929c-01f9ea7d9613.png)

2003/11/20
![20031120](https://user-images.githubusercontent.com/22968399/74783229-79165200-5262-11ea-8419-3b773df7b15d.png)

2003/11/21
![20031121](https://user-images.githubusercontent.com/22968399/74783253-86334100-5262-11ea-8541-44456eac52e9.png)

**Comment by twfang** [comment]
Tim has put together some WAM-IPE and GloTEC validation here. 

https://drive.google.com/file/d/1wSNbDE9HOn5cXhkccVz4Ek1OBL3f2etj/view

**Comment by akubaryk** [comment]
Think the sharing needs to be updated, I don't have access with my NOAA email address.

**Comment by timfullerrowell** [comment]
try it now

**Comment by akubaryk** [comment]
Yes, works now -- thanks.

**Comment by twfang** [comment]
Here are results from the WAM-IPE with the self-consistent electric field and Weimer for high-latitude potential from the weimer_ipe_fixes branch. 

20130316
![weimer_20130316](https://user-images.githubusercontent.com/22968399/76895990-ac92cf00-6856-11ea-8704-b6c0225b7c06.png)

20130317
![weimer_20130317](https://user-images.githubusercontent.com/22968399/76895999-b0beec80-6856-11ea-895b-b2e0fe847cec.png)

20130318
![weimer_20130318](https://user-images.githubusercontent.com/22968399/76896007-b4527380-6856-11ea-9d84-a5d42cfcd881.png)

20130319
![weimer_20130319](https://user-images.githubusercontent.com/22968399/76896020-bb798180-6856-11ea-8446-e5cb8d767eb8.png)

**2015**
20150316
![weimer_20150316](https://user-images.githubusercontent.com/22968399/76896066-d0561500-6856-11ea-8b8b-c2245d3d5037.png)

20150317
![weimer_20150317](https://user-images.githubusercontent.com/22968399/76896089-d8ae5000-6856-11ea-9488-bc1d2dd00a3e.png)

20150318
![weimer_20150318](https://user-images.githubusercontent.com/22968399/76896104-dd730400-6856-11ea-9d5f-fe2c514874d7.png)

20150319
![weimer_20150319](https://user-images.githubusercontent.com/22968399/76896119-e2d04e80-6856-11ea-9c7d-c4d38d657445.png)

**2003**
20031118
![weimer_20031118](https://user-images.githubusercontent.com/22968399/76896138-ebc12000-6856-11ea-9a20-b61d1a6a20ac.png)

20031119
![weimer_20031119](https://user-images.githubusercontent.com/22968399/76896157-efed3d80-6856-11ea-9add-4564aa49d26c.png)

20031120
![weimer_20031120](https://user-images.githubusercontent.com/22968399/76896164-f380c480-6856-11ea-98c6-feecba650d69.png)

20031121
![weimer_20031121](https://user-images.githubusercontent.com/22968399/76896179-f8de0f00-6856-11ea-8a32-25a3b6ddda35.png)

**Comment by twfang** [comment]
The new IPE branch appears to be stable. When I carried out the 2003 storm run, the 11/22 run was failing. It seems like WAM on 11/21 didn't write out the last record correctly. Adam is looking into this.
