### ISSUE TITLE
IPE Physics: IPE stability issue

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/IPE#3]
Under certain WAM conditions, WAM-IPE coupled run produces strange feature in O+ density, velocity, and eventually molecular ions also become NaNs. To debug this issue, we will run the model with time-vary drivers (timeobs) with empirical E fields for the 2013 St. Patrick Day storm period using 20130316 WAM initial condition under 
/scratch3/NCEPDEV/swpc/noscrub/Adam.Kubaryk/ICS/WAM-IPE/2013031600

and IPE initial condition under 
/scratch3/NCEPDEV/swpc/noscrub/refactored_ipe_input_decks/IPE_State.apex.201303160000.h5

I will then report TEC, O+ density, O+ velocity from this run to provide information to debug. Everyone who is doing the same run on different systems feels free to report plots here.

**Comment by timfullerrowell** [comment]
Houjun,
I think you are looking at a grid resolution change, not a discontinuity.
It all looks good in Tzu-Wei's plot so far.
Tim

**Comment by twfang** [comment]
@IonospherePlasmasphereElectrodynamics  
Please upload your old IPE 10 day run TEC in this issue. Thank you!

**Comment by twfang** [comment]
With George's new fixes, we are able to mitigate the NaN issue that we have been dealing with in the past few months. Here is the results of TEC after 5-day run starting from 0UT on March 16, 2013. 


March 20, 2013
![newfix_0320](https://user-images.githubusercontent.com/22968399/69566446-5848a400-0f74-11ea-837f-f085f322d6ad.png)


The plan is to merge the changes into the new repo and go from there!
