### ISSUE TITLE
implement weimer 2005 in IPE_refactor code: inside empirical E-field model

### ISSUE THREAD

**Issue by naomimaruyama** [SWPC-IPE/IPE#4]
We will need to implement weimer 2005 in IPE_refactor code inside the empirical electric field model (instead of inside the dynamo solver issue#309).
branch: “weimer2005_empirical”
many neutral features will compare with WAM after this adding.

**Comment by ZhuxiaoLi66** [comment]
The code work to include weimer2005 in ./ipelib/empirical_efield in IPE has been done, the new branch named 'weimer2005_empirical' had been push to NOAA-SWPC/IPE. the validation will start this week. 4 days run for 2013 St. Patrick storm has been performed and the reading of the input varying drivers has been verified. the potential and electric field will be verified later.

**Comment by ZhuxiaoLi66** [comment]
The Neutral Temp. & horizontal wind at 250km in the above run has been compared with WAM output and the TEC has been checked briefly.
![T_U_V_250km_2D_IPE_weimer2005_2013Mar16_2000](https://user-images.githubusercontent.com/22546571/74772461-f6a08900-5287-11ea-96da-e112f3799946.png)
![T_U_V_250km_2D_WAM_namelist__2013Mar16](https://user-images.githubusercontent.com/22546571/74772481-0029f100-5288-11ea-89b7-4a6064a3a155.png)
![T_U_V_250km_2D_IPE_weimer2005_2013Mar17_2000](https://user-images.githubusercontent.com/22546571/74772502-08822c00-5288-11ea-98dd-9c5511268830.png)
![T_U_V_250km_2D_WAM_namelist__2013Mar17](https://user-images.githubusercontent.com/22546571/74772507-0cae4980-5288-11ea-88af-04373fe829ec.png)

**Comment by ZhuxiaoLi66** [comment]
output of TEC seems get all NaNs after 53 hrs (from Mar18 06). 
![TEC_2D_IPE_weimer2005_2013Mar16](https://user-images.githubusercontent.com/22546571/74772839-a83fba00-5288-11ea-80df-53a66a2a7ec4.png)
![TEC_2D_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/74772891-b988c680-5288-11ea-8d25-f7063b6eb40d.png)
![TEC_2D_IPE_weimer2005_2013Mar18](https://user-images.githubusercontent.com/22546571/74772907-c1486b00-5288-11ea-8961-eb8fd9f1ecde.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the comparison of the Neutral Temp & Wind field between the IPE and WAM from the coupling run. 
![T_U_V_250km_2D_coupled_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75281401-265f0c00-5807-11ea-8951-86d4631eb8e4.png)
![T_U_V_250km_2D_WAM_coupled_interp_2013Mar17](https://user-images.githubusercontent.com/22546571/75281417-2b23c000-5807-11ea-8e38-9beb43360318.png)
![T_U_V_400km_2D_coupled_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75281430-3119a100-5807-11ea-87be-0646c74f57f1.png)
![T_U_V_400km_2D_WAM_coupled_interp_2013Mar17](https://user-images.githubusercontent.com/22546571/75281437-3545be80-5807-11ea-96b1-e85bf75e74a3.png)

**Comment by ZhuxiaoLi66** [comment]
The efield and potential calculated by WAM and IPE in the same coupling run has been compared as following and verified that the Werimer2005 in IPE empirical_efield works fine.

![ED1_ED2_NH_efield_IPE_weimer2005_coupled_0min](https://user-images.githubusercontent.com/22546571/75371291-b80c5f00-5883-11ea-863e-c6c354adfe25.png)
![ED1_ED2_NH_efield_WAM_weimer2005_coupled](https://user-images.githubusercontent.com/22546571/75371295-bb9fe600-5883-11ea-9946-765277670c82.png)
![ED1_ED2_NH_efield_IPE_weimer2005_coupled_30min](https://user-images.githubusercontent.com/22546571/75371308-c0649a00-5883-11ea-805b-6ab25029c922.png)
![ED1_ED2_NH_efield_WAM_weimer2005_couple_30min](https://user-images.githubusercontent.com/22546571/75371318-c5294e00-5883-11ea-9768-3225f5837ed3.png)

**Comment by ZhuxiaoLi66** [comment]
After the including of the weimer2005 into empirical_efield in IPE, TEC and the related variables (O_PLUS_2d and N2_PLUS) has been checked in both IPE standalone and coupling storm runs (20130316-0319). 
It turns out that the output of TEC and related variables have gotten many NaNs at 20130806 suddenly in the 2013 St. Pratrick storm runs (both standalone and coupling).  I tried merged the ipe_fixes into the weimer2005_empirical branch with based on the develop branch to do the IPE standalone run, the TEC NaN's problem appeared in the same way.

**Comment by ZhuxiaoLi66** [comment]
![TEC_2D_IPE_weimer2005_2013Mar18](https://user-images.githubusercontent.com/22546571/75712221-d78cf880-5c84-11ea-8c5e-60c9af70bd87.png)

![TEC_2D_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75712194-ce039080-5c84-11ea-8fc0-77c3053c7d83.png)

![O_plus_250km_IPE_weimer2005_2013Mar18](https://user-images.githubusercontent.com/22546571/75712479-394d6280-5c85-11ea-88ac-7e0ede4547aa.png)
![O_plus_250km_coupled_efield_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75712487-3ce0e980-5c85-11ea-8139-956673e3cea7.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_IPE_old_weimer_2013Mar17](https://user-images.githubusercontent.com/22546571/75712735-a5c86180-5c85-11ea-8542-073068d11b06.png)
![TEC_coupled_old_weimer_2013Mar17](https://user-images.githubusercontent.com/22546571/75712752-aeb93300-5c85-11ea-9237-24aa5a5c989e.png)

**Comment by ZhuxiaoLi66** [comment]
Based on the comparison between the weimer1996_empirical_IPE and weimer2005_empirical_IPE runs, I found that weimer2005 change the TEC very slightly compared with weimer1996, both in IPE standalone runs and the coupling runs. While the TEC in standalone IPE runs and coupling runs are quite different.  (MSIS->WAM)

**Comment by ZhuxiaoLi66** [comment]
weimer2005 is supposed to change TEC pattern, right? which IPE output variable should be changed much by the adding of weimer2005 in empirical_efield in IPE?

 
![TEC_2D_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75915943-b0fdc780-5e14-11ea-880b-55c3a8f5ba5b.png)

![TEC_IPE_old_weimer_2013Mar17](https://user-images.githubusercontent.com/22546571/75915991-bfe47a00-5e14-11ea-88df-194249fbdc0e.png)

![TEC_coupled_IPE_weimer2005_2013Mar17](https://user-images.githubusercontent.com/22546571/75916027-cbd03c00-5e14-11ea-95f1-7d9a7f042f39.png)

![TEC_coupled_old_weimer_2013Mar17](https://user-images.githubusercontent.com/22546571/75916052-d68ad100-5e14-11ea-975a-79137d513426.png)

**Comment by twfang** [comment]
The difference of TEC at mid- and low-latitudes should be really small since both packages use the same electric field in those regions. The difference should be only at higher latitudes and shouldn't be huge.

**Comment by ZhuxiaoLi66** [comment]
With Raffaele's help, now the IPE_weimer2005_empirical in NOAA-SWPC/GSMWAM-IPE is the old_IPE_weimer2005_empirical + ipefixes and can conduct coupling runs. I have merged Gorge's updated 'weimer_ipefixes' into the current IPE_weimer2005_empirical to get rid of the NaNs. It turns out the runs crashed right away after the merging. 
the run directory is /scratch1/NCEPDEV/stmp2/Zhuxiao.Li/coupled_20130316_weimer_ipefixes_empirical

**Comment by ZhuxiaoLi66** [comment]
the code package is 
/scratch1/NCEPDEV/swpc/Zhuxiao.Li/save/git/GSMWAM-IPE_weimer_ipe_fixes_empirical

**Comment by ZhuxiaoLi66** [comment]
George, could you please to have a look at the fcst file in the run dir to check if the error information was familiar to you? by the way, I set 'dynamo=F' in my run (see code package above if necessary). 
Thanks in head!

**Comment by ZhuxiaoLi66** [comment]
George, the new run with the new IPE IC file didn't crash right away and already got the output for the first hour, thanks!

**Comment by ZhuxiaoLi66** [comment]
The good news is that George's updated in weimer_ipe_fixes got rid of the NaNs in the 2013 St. Patrick storm run with the weimer2005_empirical, at least during 20130316-0319, will test for longer time.
The following is the TEC plots by the new weimer run and also the old weimer reference run. It seems the new weimer run enhance the features in Tim's validation PPT which by Heelis effect run somewhat, especially at North pole area. will make the polar projection plots later.

**Comment by ZhuxiaoLi66** [comment]
![TEC_weimer2005](https://user-images.githubusercontent.com/22546571/76348971-c2404b80-62ce-11ea-8922-dc2fdf36a9bd.png)
![TEC_weimer1996](https://user-images.githubusercontent.com/22546571/76348988-ccfae080-62ce-11ea-934d-574accc8ab16.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_1996](https://user-images.githubusercontent.com/22546571/76349108-fc115200-62ce-11ea-9a72-317fef2cd471.png)

**Comment by ZhuxiaoLi66** [comment]
The following polar plots for both the empirical new weimer and old weimer runs.

![TEC_NH_polar_coupled_weimer_ipefixes_empirical_2013Mar17](https://user-images.githubusercontent.com/22546571/76355311-b0b07100-62d9-11ea-92e8-08ddd9d4e536.png)
![TEC_NH_polar_coupled_weimer1996_empirical_2013Mar17](https://user-images.githubusercontent.com/22546571/76355323-b5752500-62d9-11ea-8ca8-2e7405fd0305.png)

**Comment by ZhuxiaoLi66** [comment]
the border is 60N for the above plots. 
zoom out the TEC (at 30N) from new weimer run.  

![TEC_30N_weimer2005](https://user-images.githubusercontent.com/22546571/76355640-44823d00-62da-11ea-8b7b-030cad635faf.png)

**Comment by ZhuxiaoLi66** [comment]
Over the south hemisphere, the empirical new weimer also does a good job, we can see the built up TEC tough is very clear on 12 UT of 20130317. 

![TEC_SH_polar_60deg_coupled_weimer_ipefixes_empirical_2013Mar17](https://user-images.githubusercontent.com/22546571/76358852-cc1e7a80-62df-11ea-8636-91865834a7e8.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots are the 10 days average TEC comparison between kmax140 and kmax180 WAM-IPE self-consistent electric runs.The Fig3 is (TEC180-TEC140)/TEC140*100. TPavg is the global mean of change percentage , TPavg0 is the global mean of decrease area (except TP>0 area).
![Capture](https://user-images.githubusercontent.com/22546571/76665235-aa75fb00-654c-11ea-8bbd-4a5c7d868887.PNG)
![Capture1](https://user-images.githubusercontent.com/22546571/76665247-b792ea00-654c-11ea-81ad-d01467e8f42f.PNG)
![Capture5](https://user-images.githubusercontent.com/22546571/76665253-bb267100-654c-11ea-95f7-0ac726461af3.PNG)

**Comment by twfang** [comment]
The code has been tested and merged into IPE (PR #28 ).
