### ISSUE TITLE
Read apex grid parameters from grid file

### ISSUE THREAD

**Issue by rmontuoro** [SWPC-IPE/IPE#8]
For consistency, and to prevent mistakes, the following parameters should be read from the grid file:

- `nFluxTube`
- `NLP`
- `NMP`

instead of the current `&SpaceManagement` namelist.

If needed, `NPTS2D` could then be computed from the parameters above.

**Comment by twfang** [comment]
@rmontuoro , just want to check with you to make sure this issue has been taken care of and can be closed. Thank you!

**Comment by rmontuoro** [comment]
Issue resolved with commit [1d9997b](https://github.com/NOAA-SWPC/IPE/commit/1d9997b9a4d3774978469da330c7e0848b227717)
